/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package androidFile.AlmaWiFinder;

public final class R {
    public static final class anim {
        public static final int magnify=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int download=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int lista=0x7f020003;
    }
    public static final class id {
        public static final int address=0x7f060003;
        public static final int description=0x7f060004;
        public static final int distance=0x7f060007;
        public static final int gomaps=0x7f060006;
        public static final int list=0x7f060005;
        public static final int mapSpace=0x7f060008;
        public static final int name=0x7f060002;
        public static final int text1=0x7f060000;
        public static final int viewLayout=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int row=0x7f030001;
        public static final int view=0x7f030002;
    }
    public static final class string {
        public static final int alert_dialog_ok=0x7f050007;
        public static final int alert_dialog_two_buttons_title=0x7f050006;
        public static final int app_name=0x7f050000;
        public static final int menu_Download=0x7f050001;
        public static final int menu_List=0x7f050002;
        public static final int styled_textAddress=0x7f050003;
        public static final int styled_textDesc=0x7f050004;
        public static final int styled_textName=0x7f050005;
    }
}
